### ISSUE TITLE
playlist song

### ISSUE THREAD

**Issue by jonathanarde** [TheoTech/glorifycc#24]
when song is deleted from database, song in the playlist schema is not deleted

**Comment by chrislim** [comment]
The right behavior is that playlists that include the song should be deleted.
Suggestion: 
* Add a flag to mark a song as deleted without actually removing it from the database.
* Create a separate worker job that will permanently delete any songs as well as clean up all of their references.
* in the UI do not show the deleted songs, just let the user know it has been deleted, until everything is cleaned up.

**Comment by nylim11** [comment]
Use case to consider: as a user, I would be concerned if a song were to just disappear from a playlist I made recently. Ideally, would have some way to know if a song is flagged for deletion/no longer accessible.
