### ISSUE TITLE
song schema

### ISSUE THREAD

**Issue by jonathanarde** [TheoTech/glorifycc#27]
need to delete oriSong filed in song schema

**Comment by chrislim** [comment]
Cleanup this field in the database. Check the codebase to ensure it's not being used anywhere (search for every instance). This field is replaced with the source field. If a song has a source, then that source is its original.

**Comment by daxkerchner** [comment]
It's in two places

![image](https://cloud.githubusercontent.com/assets/5436546/20498363/c80a610c-afe1-11e6-8e47-d3301a8e8b54.png)
