### ISSUE TITLE
song selected

### ISSUE THREAD

**Issue by jonathanarde** [TheoTech/glorifycc#29]
lyric display is wrong

**Comment by chrislim** [comment]
![image](https://cloud.githubusercontent.com/assets/469630/20495163/ca632e1e-afd4-11e6-87de-93c4254b1c3e.png)

**Comment by chrislim** [comment]
wipe out the database and run dax's script

**Comment by chrislim** [comment]
we think its the migration script that causes this bug,

**Comment by chrislim** [comment]
We found that for the hosanna song, the template was showing each stanza as a column instead of as a row inside of a column.
